# Generated by Django 5.0.3 on 2024-04-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0002_visaapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
